baseurl = "https://binc4t.github.io"
title = "where dream begins!"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "bincat"
  info = "Code for Love"
#  description = "where dream beagins"
  keywords = ""
  avatarurl = "https://yyypics.oss-cn-beijing.aliyuncs.com/IMG_1262.jpg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# 代码高亮
[markup.highlight]
style = 'github' # 样式参考 https://swapoff.org/chroma/playground
[markup.goldmark.renderer]
  unsafe = true # 默认值不支持在 markdown 中写 html，需改成 true 开启

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Reading"
  weight = 2
  url = "reading"
[[menu.main]]
  name = "Friend"
  weight = 3
  url = "friend"
[[menu.main]]
  name = "Whisper"
  weight = 3
  url = "whisper"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about"

