baseurl = "https://anccy.github.io"
title = "where dream begins!"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Anccy"
  info = "Code for Love"
#  description = "where dream beagins"
  keywords = "web3"
  avatarurl = "https://yyypics.oss-accelerate.aliyuncs.com/avatar.jpeg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Reading"
  weight = 2
  url = "reading"